version: '3.8'
services:
  prism:
    image: stoplight/prism:latest
    command: mock /openapi.yaml --host 0.0.0.0 --port 4040
    ports:
      - "4040:4040"
    volumes:
      - ./openapi.yaml:/openapi.yaml
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./openapi.yaml:/openapi.yaml

  